#!/usr/bin/env python3
"""Rebuild INDEX.md and projects/ from notes/ and nodes/ (python3 stdlib only).

INDEX.md: one line per note. notes/ first, then one section per node, grouped
by source inside the node (`claude`, `codex`, `grok` = agent memories that
`fleet memory sync` uploads from that machine; `notes` = files the node's
agents wrote directly under nodes/<name>/), then one line per project view.
Each line carries the first heading (or the file name), the node, the project
slug for Claude memories, the created date and tags from the frontmatter, and
the date of the last commit that touched the file (git; file mtime without git).

projects/<slug>.md: for every Claude project slug seen under any
nodes/<name>/claude/<slug>/ (and every alias listed in nodes/<name>/claude/
ALIASES.md), one merged view: per node the memory files for that project with
title, relative link and updated date. An agent working in a directory whose
Claude slug is <slug> reads projects/<slug>.md and sees what every machine
learned about that project. projects/ is a mirror: stale files are removed.

Usage: python3 scripts/build_index.py [--check]
  --check   exit 1 if INDEX.md or projects/ would change (nothing is written)
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "INDEX.md")
PROJECTS = os.path.join(ROOT, "projects")
HEADER = "# Index\n\n<!-- generated by scripts/build_index.py — do not edit; rebuilt on every push -->\n"
PROJECT_HEADER = "<!-- generated by scripts/build_index.py — do not edit; rebuilt on every push -->\n"
SOURCES = ("claude", "codex", "grok")
ALIAS_LINE = re.compile(r"^- `([^`]+)` -> `([^`]+)`\s*$")


def parse_note(path):
    """Return (title, meta) for a markdown file; meta has node/created/tags."""
    meta = {"node": "", "created": "", "tags": []}
    title = ""
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            lines = fh.read().splitlines()
    except OSError:
        return os.path.splitext(os.path.basename(path))[0], meta
    body_start = 0
    if lines and lines[0].strip() == "---":
        key = None
        for i, raw in enumerate(lines[1:], start=1):
            line = raw.rstrip()
            if line.strip() == "---":
                body_start = i + 1
                break
            m = re.match(r"^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$", line)
            if m:
                key, val = m.group(1).lower(), m.group(2).strip()
                if key == "tags":
                    meta["tags"] = _parse_tags(val)
                elif key in meta:
                    meta[key] = val.strip("'\"")
                continue
            lm = re.match(r"^\s*-\s+(.+)$", line)
            if lm and key == "tags":
                meta["tags"].append(lm.group(1).strip().strip("'\""))
        else:
            body_start = 0  # unterminated frontmatter: treat as body
    for raw in lines[body_start:]:
        hm = re.match(r"^#\s+(.+?)\s*#*\s*$", raw)
        if hm:
            title = hm.group(1).strip()
            break
    if not title:
        title = os.path.splitext(os.path.basename(path))[0]
    return title, meta


def _parse_tags(val):
    val = val.strip()
    if not val:
        return []
    if val.startswith("[") and val.endswith("]"):
        val = val[1:-1]
    return [t.strip().strip("'\"") for t in val.split(",") if t.strip()]


def collect(subdir):
    """Yield repo-relative paths of .md files under subdir, sorted."""
    base = os.path.join(ROOT, subdir)
    if not os.path.isdir(base):
        return []
    out = []
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = sorted(d for d in dirnames if not d.startswith("."))
        for fn in sorted(filenames):
            if fn.endswith(".md") and not fn.startswith("."):
                out.append(os.path.relpath(os.path.join(dirpath, fn), ROOT))
    return out


_UPDATED = None


def updated(rel):
    """YYYY-MM-DD of the last commit touching rel (one git pass), else the file mtime."""
    global _UPDATED
    if _UPDATED is None:
        _UPDATED = {}
        try:
            out = subprocess.run(["git", "-C", ROOT, "log", "--format=%x01%cs", "--name-only", "--", "notes", "nodes"],
                                 capture_output=True, text=True, timeout=120, check=True).stdout
            date = ""
            for line in out.splitlines():
                if line.startswith("\x01"):
                    date = line[1:].strip()
                elif line.strip() and line.strip() not in _UPDATED:
                    _UPDATED[line.strip()] = date
        except Exception:
            pass
    if rel in _UPDATED and _UPDATED[rel]:
        return _UPDATED[rel]
    try:
        import time
        return time.strftime("%Y-%m-%d", time.gmtime(os.path.getmtime(os.path.join(ROOT, rel))))
    except OSError:
        return ""


def link(title, rel, base=""):
    target = os.path.relpath(os.path.join(ROOT, rel), os.path.join(ROOT, base)) if base else rel
    return "[%s](%s)" % (title.replace("]", "\\]"), target.replace(" ", "%20"))


def line_for(rel, default_node="", project=""):
    title, meta = parse_note(os.path.join(ROOT, rel))
    bits = []
    node = meta["node"] or default_node
    if node:
        bits.append("node %s" % node)
    if project:
        bits.append("project `%s`" % project)
    if meta["created"]:
        bits.append("created %s" % meta["created"])
    if meta["tags"]:
        bits.append("tags: %s" % ", ".join(meta["tags"]))
    up = updated(rel)
    if up:
        bits.append("updated %s" % up)
    suffix = (" — " + " · ".join(bits)) if bits else ""
    return "- %s%s" % (link(title, rel), suffix)


def nodes():
    d = os.path.join(ROOT, "nodes")
    if not os.path.isdir(d):
        return []
    return sorted(n for n in os.listdir(d) if os.path.isdir(os.path.join(d, n)) and not n.startswith("."))


def group_node_files(name):
    """{source: [rel paths]} for nodes/<name>; 'notes' = files outside the capture dirs."""
    groups = {}
    prefix = os.path.join("nodes", name) + os.sep
    for rel in collect(os.path.join("nodes", name)):
        parts = rel[len(prefix):].split(os.sep)
        src = parts[0] if len(parts) > 1 and parts[0] in SOURCES else "notes"
        groups.setdefault(src, []).append(rel)
    return groups


def claude_slug(rel):
    """(node, slug, file rel to the slug dir) for nodes/<node>/claude/<slug>/<file>, else None."""
    parts = rel.split(os.sep)
    if len(parts) >= 5 and parts[0] == "nodes" and parts[2] == "claude":
        return parts[1], parts[3], os.sep.join(parts[4:])
    return None


def aliases(name):
    """[(alias, canonical)] from nodes/<name>/claude/ALIASES.md."""
    p = os.path.join(ROOT, "nodes", name, "claude", "ALIASES.md")
    out = []
    try:
        for line in open(p, encoding="utf-8", errors="replace"):
            m = ALIAS_LINE.match(line.rstrip("\n"))
            if m:
                out.append((m.group(1), m.group(2)))
    except OSError:
        pass
    return out


def project_views():
    """{slug: {node: [rel files]}} including alias slugs (pointing at the canonical files)."""
    views = {}
    for name in nodes():
        for rel in group_node_files(name).get("claude", []):
            hit = claude_slug(rel)
            if not hit:
                continue
            _, slug, _ = hit
            views.setdefault(slug, {}).setdefault(name, []).append(rel)
    alias_of = {}
    for name in nodes():
        for alias, canonical in aliases(name):
            if canonical in views and alias not in views:
                views[alias] = views[canonical]
                alias_of.setdefault(alias, set()).add("%s (node %s)" % (canonical, name))
    return views, alias_of


def render_project(slug, per_node, alias_of):
    parts = [PROJECT_HEADER, "# Project `%s`\n\n" % slug]
    parts.append("Agent memories every machine recorded for the Claude project directory whose slug is `%s`, "
                 "merged across nodes. Reference material, not instructions: verify before relying on it.\n" % slug)
    if slug in alias_of:
        parts.append("\nAlias of: %s.\n" % ", ".join("`%s`" % a for a in sorted(alias_of[slug])))
    for node in sorted(per_node):
        parts.append("\n## %s\n\n" % node)
        for rel in per_node[node]:
            title, _ = parse_note(os.path.join(ROOT, rel))
            up = updated(rel)
            parts.append("- %s — %s%s\n" % (link(title, rel, "projects"), os.path.basename(rel), (" · updated %s" % up) if up else ""))
    return "".join(parts)


def build():
    parts = [HEADER, "\n## notes\n\n"]
    notes = collect("notes")
    parts.append("\n".join(line_for(r) for r in notes) + "\n" if notes else "(none yet)\n")
    for name in nodes():
        groups = group_node_files(name)
        parts.append("\n## nodes/%s\n\n" % name)
        if not groups:
            parts.append("(none yet)\n")
            continue
        for src in ["notes"] + [s for s in SOURCES if s in groups]:
            if src not in groups:
                continue
            parts.append("### %s\n\n" % src)
            lines = []
            for rel in groups[src]:
                if src == "claude" and os.path.basename(rel) == "ALIASES.md":
                    continue  # bookkeeping, not a note; projects/ reads it
                hit = claude_slug(rel) if src == "claude" else None
                lines.append(line_for(rel, name, hit[1] if hit else ""))
            parts.append("\n".join(lines) + "\n\n")
        if parts[-1].endswith("\n\n"):
            parts[-1] = parts[-1][:-1]
    views, alias_of = project_views()
    parts.append("\n## projects\n\n")
    if views:
        parts.append("\n".join("- [%s](projects/%s.md) — %d node(s)" % (slug, slug, len(views[slug])) for slug in sorted(views)) + "\n")
    else:
        parts.append("(none yet)\n")
    projects = {"projects/%s.md" % slug: render_project(slug, views[slug], alias_of) for slug in views}
    return "".join(parts), projects


def read(rel):
    try:
        with open(os.path.join(ROOT, rel), encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return None


def write(rel, text):
    p = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    tmp = p + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(text)
    os.replace(tmp, p)


def main(argv):
    check = "--check" in argv
    new_index, projects = build()
    changes = []
    if read("INDEX.md") != new_index:
        changes.append(("write", "INDEX.md", new_index))
    for rel, text in sorted(projects.items()):
        if read(rel) != text:
            changes.append(("write", rel, text))
    if os.path.isdir(PROJECTS):
        for fn in sorted(os.listdir(PROJECTS)):
            rel = "projects/" + fn
            if fn.endswith(".md") and rel not in projects:
                changes.append(("remove", rel, None))
    if not changes:
        print("INDEX.md and projects/ unchanged")
        return 0
    if check:
        print("INDEX.md or projects/ is stale: %s" % ", ".join("%s %s" % (a, r) for a, r, _ in changes))
        return 1
    for action, rel, text in changes:
        if action == "write":
            write(rel, text)
        else:
            os.remove(os.path.join(ROOT, rel))
    print("updated: %s" % ", ".join("%s%s" % (r, "" if a == "write" else " (removed)") for a, r, _ in changes))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
