#!/usr/bin/env python3
"""Rebuild INDEX.md from notes/ and nodes/<name>/ (python3 stdlib only).

One line per note, grouped: notes/ first, then one section per node. Each line
carries the first heading (or the file name), the node, the created date, and
the tags from the frontmatter. Writes INDEX.md only when the content changed.

Usage: python3 scripts/build_index.py [--check]
  --check   exit 1 if INDEX.md would change (nothing is written)
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "INDEX.md")
HEADER = "# Index\n\n<!-- generated by scripts/build_index.py — do not edit; rebuilt on every push -->\n"


def parse_note(path):
    """Return (title, meta) for a markdown file; meta has node/created/tags."""
    meta = {"node": "", "created": "", "tags": []}
    title = ""
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            lines = fh.read().splitlines()
    except OSError:
        return os.path.splitext(os.path.basename(path))[0], meta
    body_start = 0
    if lines and lines[0].strip() == "---":
        key = None
        for i, raw in enumerate(lines[1:], start=1):
            line = raw.rstrip()
            if line.strip() == "---":
                body_start = i + 1
                break
            m = re.match(r"^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$", line)
            if m:
                key, val = m.group(1).lower(), m.group(2).strip()
                if key == "tags":
                    meta["tags"] = _parse_tags(val)
                elif key in meta:
                    meta[key] = val.strip("'\"")
                continue
            lm = re.match(r"^\s*-\s+(.+)$", line)
            if lm and key == "tags":
                meta["tags"].append(lm.group(1).strip().strip("'\""))
        else:
            body_start = 0  # unterminated frontmatter: treat as body
    for raw in lines[body_start:]:
        hm = re.match(r"^#\s+(.+?)\s*#*\s*$", raw)
        if hm:
            title = hm.group(1).strip()
            break
    if not title:
        title = os.path.splitext(os.path.basename(path))[0]
    return title, meta


def _parse_tags(val):
    val = val.strip()
    if not val:
        return []
    if val.startswith("[") and val.endswith("]"):
        val = val[1:-1]
    return [t.strip().strip("'\"") for t in val.split(",") if t.strip()]


def collect(subdir):
    """Yield repo-relative paths of .md files under subdir, sorted."""
    base = os.path.join(ROOT, subdir)
    if not os.path.isdir(base):
        return []
    out = []
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = sorted(d for d in dirnames if not d.startswith("."))
        for fn in sorted(filenames):
            if fn.endswith(".md") and not fn.startswith("."):
                out.append(os.path.relpath(os.path.join(dirpath, fn), ROOT))
    return out


def line_for(rel, default_node=""):
    title, meta = parse_note(os.path.join(ROOT, rel))
    bits = []
    node = meta["node"] or default_node
    if node:
        bits.append("node %s" % node)
    if meta["created"]:
        bits.append("created %s" % meta["created"])
    if meta["tags"]:
        bits.append("tags: %s" % ", ".join(meta["tags"]))
    suffix = (" — " + " · ".join(bits)) if bits else ""
    return "- [%s](%s)%s" % (title.replace("]", "\\]"), rel.replace(" ", "%20"), suffix)


def build():
    parts = [HEADER, "\n## notes\n\n"]
    notes = collect("notes")
    parts.append("\n".join(line_for(r) for r in notes) + "\n" if notes else "(none yet)\n")
    nodes_dir = os.path.join(ROOT, "nodes")
    if os.path.isdir(nodes_dir):
        for name in sorted(d for d in os.listdir(nodes_dir)
                           if os.path.isdir(os.path.join(nodes_dir, d)) and not d.startswith(".")):
            files = collect(os.path.join("nodes", name))
            parts.append("\n## nodes/%s\n\n" % name)
            parts.append("\n".join(line_for(r, name) for r in files) + "\n" if files else "(none yet)\n")
    return "".join(parts)


def main(argv):
    check = "--check" in argv
    new = build()
    try:
        with open(INDEX, encoding="utf-8") as fh:
            old = fh.read()
    except OSError:
        old = None
    if old == new:
        print("INDEX.md unchanged")
        return 0
    if check:
        print("INDEX.md is stale")
        return 1
    tmp = INDEX + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(new)
    os.replace(tmp, INDEX)
    print("INDEX.md updated")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
